# Generated by Django 4.0.5 on 2022-06-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MemeDetector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnnimage',
            old_name='filename',
            new_name='name',
        ),
    ]
