# Generated by Django 4.0.5 on 2022-06-23 04:05

import MemeDetector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemeDetector', '0002_rename_filename_cnnimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnnimage',
            name='image',
            field=models.ImageField(upload_to=MemeDetector.models.update_filename),
        ),
    ]
