# Generated by Django 4.0.5 on 2022-06-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemeDetector', '0003_alter_cnnimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnnimage',
            name='was_processed',
            field=models.BooleanField(default=False),
        ),
    ]
