# Generated by Django 4.0.5 on 2022-06-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemeDetector', '0004_cnnimage_was_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnnimage',
            name='is_meme',
        ),
        migrations.AddField(
            model_name='cnnimage',
            name='meme_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cnnimage',
            name='no_meme_confidence',
            field=models.IntegerField(default=0),
        ),
    ]
