# Generated by Django 4.0.5 on 2022-07-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometextcards',
            name='url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
