# Generated by Django 4.0.5 on 2022-07-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_rename_hometextcards_hometextcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometextcard',
            name='internal_url',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hometextcard',
            name='internal_url_verbose',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hometextcard',
            name='url_verbose',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
