# Generated by Django 4.0.5 on 2022-07-03 03:28

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_hometextcard_internal_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometextcard',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='djangodbmodelsfieldscharfield', editable=False, populate_from=models.CharField(max_length=100)),
        ),
    ]
