# Generated by Django 4.0.5 on 2022-07-03 03:29

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0005_hometextcard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometextcard',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from=models.CharField(max_length=100)),
        ),
    ]
